// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataLayer.Models
{
    public partial class Product
    {
        public Product()
        {
            CartItems = new HashSet<CartItem>();
            Pictures = new HashSet<Picture>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal? SalePrice { get; set; }
        public decimal? Discount { get; set; }
        public string ShortDetails { get; set; }
        public string Description { get; set; }
        public int? Stock { get; set; }
        public string Brand { get; set; }
        public bool? Sale { get; set; }
        public string Tags { get; set; }
        public string Colors { get; set; }
        public int? CategoryId { get; set; }
        public int? CompanyId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}